language: php

php: [5.3, 5.4, 5.5, hhvm]

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  - CSS_SELECTOR_VERSION='2.0.*'
  - CSS_SELECTOR_VERSION='2.1.*'
  - CSS_SELECTOR_VERSION='2.2.*'
  - CSS_SELECTOR_VERSION='2.3.*@dev'

before_script:
  - composer require --no-update symfony/css-selector=$CSS_SELECTOR_VERSION
  - composer install --dev --prefer-source

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
