language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*
  - SYMFONY_VERSION=5.2.*

jobs:
  include:
  - php: 8.0
    env: SYMFONY_VERSION=6.0.x@dev

cache:
  directories:
    - $HOME/symfony-bridge/.phpunit

install:
  - composer require symfony/css-selector:$SYMFONY_VERSION
  - vendor/bin/simple-phpunit install

script: XDEBUG_MODE=coverage vendor/bin/simple-phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
